### ISSUE TITLE
Exception: This method should be invoked with distinct vars

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#15]
Hi Glauco,

It seems I'm stuck in a loop with this exception:
```
I am the worker thread!!!!!!!!!
[Trace - 09:39:54] Received notification 'textDocument/publishDiagnostics'.
validateFullDocument - this.mmParser:[object Object]
before mmpParser.parse()
after mmpParser.parse()
[Trace - 09:39:54] Received notification 'textDocument/publishDiagnostics'.
validateFullDocument - this.mmParser:[object Object]
before mmpParser.parse()
after mmpParser.parse()
[Trace - 09:39:54] Received notification 'textDocument/publishDiagnostics'.
validateFullDocument - this.mmParser:[object Object]
before mmpParser.parse()
/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mm/DisjointVarMap.js:14
            throw new Error("This method should be invoked with distinct vars");
                  ^

Error: This method should be invoked with distinct vars
    at DisjointVarMap.add (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mm/DisjointVarMap.js:14:19)
    at MmpProof.addDisjointVarStatement (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpProof.js:258:23)
    at MmpParser.addDisjointVarConstraint (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpParser.js:402:74)
    at MmpParser.createMmpStatementFromStepTokens (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpParser.js:460:18)
    at MmpParser.createNextMmpStatement (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpParser.js:475:14)
    at MmpParser.createMmpStatements (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpParser.js:613:26)
    at MmpParser.parse (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpParser.js:697:14)
    at MmpValidator.validateFullDocumentText (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpValidator.js:47:24)
    at MmpValidator.validateFullDocument (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/mmp/MmpValidator.js:65:22)
    at OnDidChangeContentHandler.validateTextDocument (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/server/out/languageServerHandlers/OnDidChangeContentHandler.js:114:22)

Node.js v20.9.0
[Info  - 09:39:54] Connection to server got closed. Server will restart.
[Error - 09:39:54] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.14/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:337:12)
[Trace - 09:39:54] Sending request 'initialize - (0)'.
[Trace - 09:39:55] Received response 'initialize - (0)' in 142ms.
[Trace - 09:39:55] Sending notification 'initialized'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Sending notification 'textDocument/didOpen'.
[Trace - 09:39:55] Received request 'client/registerCapability - (0)'.
[Trace - 09:39:55] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 09:39:55] Sending request 'textDocument/codeAction - (1)'.
```

**Comment by glacode** [comment]
Thanks, Thierry

I'll try it in the dev environment to see if I can reproduce it.

If you give it the exact same "offending" .mmp in a completely new VSCode session, is the error still there?

p.s.
I'm a bit challenged in the "real world", now; something I hope to fix in the next few months, and then I will be back at full speed on yamma. Please, keep posting the issues even though I can't fix them immediately

**Comment by glacode** [comment]
Well, the message clearly says that

$d z z

is the culprit. Of course, I have to manage it in a gentler way.

I love when I can add a new simple unit test :-)
