### ISSUE TITLE
Progress handler for token TEST-PROGRESS-TOKEN already registered

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#3]
Hi Glauco!

I get this error in the output when activating the Yamma VSCode plugin:
```
before loadNewTheorySync - GlobalState.mmParser = undefined
before loadNewTheorySync - GlobalState.mmParser = undefined
[Error - 14:39:06] Registering progress handler for token TEST-PROGRESS-TOKEN failed.
Error: Progress handler for token TEST-PROGRESS-TOKEN already registered
	at Object.onProgress (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:876:23)
	at LanguageClient.onProgress (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-languageclient/lib/common/client.js:1913:45)
	at new ProgressPart (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-languageclient/lib/common/progressPart.js:16:41)
	at createHandler (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-languageclient/lib/common/progress.js:30:34)
	at handleRequest (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:405:41)
	at processMessageQueue (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:286:17)
	at Immediate._onImmediate (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:466:21)
loadNewTheoryIfNeeded_1
loadNewTheoryIfNeeded_2
Reading file line by line with readline done.
The script uses approximately 60.79 MB
inizio parsing: Sat Apr 29 2023 14:39:06 GMT+0200 (Central European Summer Time)
verifying : 1000 : simpli
verifying : 2000 : dedlem0b
[.../...]
```
Could that be a problem?

**Comment by tirix** [comment]
Actually I see the same error later down the output, too:
```
verifying : 96000 : mdandyvrx8
fine parsing: Sat Apr 29 2023 14:39:11 GMT+0200 (Central European Summer Time)
after loadNewTheorySync - GlobalState.mmParser = [object Object]
before loadStepSuggestionModelAsync
after loadStepSuggestionModelAsync
before updateStatistics
after updateStatistics
before createParseNodesForAssertions
this.globalState.mmParser.isParsingComplete=true
this.globalState.mmParser.parseFailed=false
I am the Main thread!!!!!!!: labelToFormulaMap.size = 96945
after createParseNodesForAssertions
/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Request window/workDoneProgress/create failed with message: Progress handler for token TEST-PROGRESS-TOKEN already registered
    at handleResponse (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/server/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/server/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/Users/Thierry/.vscode/extensions/glacode.yamma-0.0.2/server/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
[Info  - 14:39:12] Connection to server got closed. Server will restart.
```

**Comment by glacode** [comment]
Hi Thierry,

do you get it every time the extension is activated?

**Comment by glacode** [comment]
Do you have another .mmp extension running?

**Comment by tirix** [comment]
Hi Glauco,

I got it yesterday and today every time the extension was activated.
I disabled the other .mmp extension before trying.

However in the mean time I tried using the `.mms` file and right now I do not see this message anymore. I can only assume I got it because I activated Yamma twice for some reason.

**Comment by tirix** [comment]
I have not reproduced this issue even after uninstalling/reinstalling the extension, so I'm going to close this issue for now.
It was probably a wrong manipulation on my side, even though I can't point which one.
